<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset = utf-8">
		<title>Mini site</title>
	</head>
	<body>
        <div class = "menu">
            <a href="index.php?controller=books&amp;action=list">Books</a>
            <a href="index.php?controller=feedback">Feedback messages</a>
            <?php if(isset($_SESSION['user'])) :?>
                <a href="index.php?controller=security&amp;logout=1">Logout</a>
                <b><?php echo "Welcome  ".$_SESSION['user'];?></b>
            <?php else :?>
                <a href="index.php?controller=security&amp;login=1">Log in</a>
            <?php endif;?>
        </div>
        <hr>
        <div class="content">
            <p><?=$msg;?></p>
            <?=$content?>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>
        <div class="footer">
            some footer
        </div>
    </body>
</html>