<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset = utf-8">
		<title>Login page</title>
	</head>
	<body>
        <h1>Log in</h1>
        <form method="post">
            <input type="text" name="email" value="<?=requestPost('email')?>" placeholder="email"><br/>
            <input type="text" name="password" placeholder="password"><br/>
            <button>Go</button>
        </form>
    </body>
</html>